# Import Package

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

# Import Data

In [2]:
df = pd.read_csv('kidney.csv')

In [3]:
df.head()

id  gravity    ph  osmo  cond  urea  calc  target
0   0    1.013  6.19   443  14.8   124  1.45       0
1   1    1.025  5.40   703  23.6   394  4.18       0
2   2    1.009  6.13   371  24.5   159  9.04       0
3   3    1.021  4.91   442  20.8   398  6.63       1
4   4    1.021  5.53   874  17.8   385  2.21       1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       414 non-null    int64  
 1   gravity  414 non-null    float64
 2   ph       414 non-null    float64
 3   osmo     414 non-null    int64  
 4   cond     414 non-null    float64
 5   urea     414 non-null    int64  
 6   calc     414 non-null    float64
 7   target   414 non-null    int64  
dtypes: float64(4), int64(4)
memory usage: 26.0 KB


# Partition Data

In [6]:
y = df['target'] # Dependent, Predict
#X = df[['gravity','ph','osmo','cond','urea']] # In Dependent - Features - Variables

X = df.drop(['target','id'], axis = 1)

In [7]:
X.head()

gravity    ph  osmo  cond  urea  calc
0    1.013  6.19   443  14.8   124  1.45
1    1.025  5.40   703  23.6   394  4.18
2    1.009  6.13   371  24.5   159  9.04
3    1.021  4.91   442  20.8   398  6.63
4    1.021  5.53   874  17.8   385  2.21

# Model

In [8]:
# 1 - Import Package

# 2 - Create Instance
model = LogisticRegression()

# 3 - Fit Instance
model.fit(X, y)

LogisticRegression()

In [9]:
# Coeff/Slope - m1, m2, m3, m4
model.coef_

array([[-7.94735110e-01, -1.95605436e-02, -2.31201150e-04,
        -3.41631060e-04,  9.87949001e-04,  3.53689594e-01]])

In [10]:
# C 
model.intercept_

array([-0.83745029])

In [11]:
# 4 - Predict
y_pred = model.predict(X)

In [12]:
y_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,

In [18]:
# 4 - Predict Probability
y_pred_proba = model.predict_proba(X)

In [30]:
y_pred_proba[:,1]

array([0.22518197, 0.48485383, 0.81773074, 0.70764045, 0.30934546,
       0.33365702, 0.28810877, 0.21740511, 0.2641232 , 0.43991568,
       0.16712089, 0.2205409 , 0.6761209 , 0.48602228, 0.19807541,
       0.16299831, 0.29335012, 0.1974045 , 0.34830713, 0.82845271,
       0.22387017, 0.4917004 , 0.51142221, 0.24501375, 0.34478086,
       0.20262916, 0.31283904, 0.37212542, 0.35156588, 0.42803617,
       0.30000928, 0.21921694, 0.25310826, 0.30592776, 0.22202691,
       0.21154289, 0.52221261, 0.2058208 , 0.50163925, 0.20029098,
       0.31949275, 0.33684134, 0.28822424, 0.29340288, 0.32442635,
       0.71981636, 0.22559522, 0.72250035, 0.95399512, 0.30126625,
       0.34406347, 0.75319355, 0.2343965 , 0.75958723, 0.29650896,
       0.62318885, 0.18988963, 0.6961703 , 0.50063065, 0.47545519,
       0.28900311, 0.23996154, 0.75943216, 0.65658189, 0.52642312,
       0.31316888, 0.25046941, 0.34713481, 0.15304005, 0.23153888,
       0.86233769, 0.48791608, 0.61758912, 0.79074651, 0.29376

# Performance

In [17]:
# y, y_pred
from sklearn.metrics import classification_report

# Calculate Mean Squared Error
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.85      0.77       230
           1       0.75      0.57      0.65       184

    accuracy                           0.72       414
   macro avg       0.73      0.71      0.71       414
weighted avg       0.73      0.72      0.72       414

