# Import Package

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

# Import Data

In [2]:
df = pd.read_csv('kidney.csv')

In [3]:
df.head()

id  gravity    ph  osmo  cond  urea  calc  target
0   0    1.013  6.19   443  14.8   124  1.45       0
1   1    1.025  5.40   703  23.6   394  4.18       0
2   2    1.009  6.13   371  24.5   159  9.04       0
3   3    1.021  4.91   442  20.8   398  6.63       1
4   4    1.021  5.53   874  17.8   385  2.21       1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       414 non-null    int64  
 1   gravity  414 non-null    float64
 2   ph       414 non-null    float64
 3   osmo     414 non-null    int64  
 4   cond     414 non-null    float64
 5   urea     414 non-null    int64  
 6   calc     414 non-null    float64
 7   target   414 non-null    int64  
dtypes: float64(4), int64(4)
memory usage: 26.0 KB


# Partition Data

In [6]:
y = df['target'] # Dependent, Predict
#X = df[['gravity','ph','osmo','cond','urea']] # In Dependent - Features - Variables

X = df.drop(['target','id'], axis = 1)

In [7]:
X.head()

gravity    ph  osmo  cond  urea  calc
0    1.013  6.19   443  14.8   124  1.45
1    1.025  5.40   703  23.6   394  4.18
2    1.009  6.13   371  24.5   159  9.04
3    1.021  4.91   442  20.8   398  6.63
4    1.021  5.53   874  17.8   385  2.21

# Model

In [8]:
# 1 - Import Package

# 2 - Create Instance
model = LogisticRegression()

# 3 - Fit Instance
model.fit(X, y)

LogisticRegression()

In [9]:
# Coeff/Slope - m1, m2, m3, m4
model.coef_

array([[-7.94735110e-01, -1.95605436e-02, -2.31201150e-04,
        -3.41631060e-04,  9.87949001e-04,  3.53689594e-01]])

In [10]:
# C 
model.intercept_

array([-0.83745029])

In [11]:
# 4 - Predict
y_pred = model.predict(X)

In [12]:
y_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,

# Performance

In [38]:
# y, y_pred
from sklearn.metrics import mean_squared_error

# Calculate Mean Squared Error
mse = mean_squared_error(y, y_pred)
print("Mean Squared Error:", mse)

# Calculate Sum of Squared Errors
sse = np.sum((y - y_pred) ** 2)
print("Sum of Squared Errors:", sse)

Mean Squared Error: 1148776.0770884347
Sum of Squared Errors: 222372031570.23956


In [ ]:
Mean Squared Error: 1506485.8136356685
Sum of Squared Errors: 291614978402.8973